replicaCount: 1
namespace: test-delete-ns
image:
  repository: amankinenko/ks-guestbook-demo
  tag: 0.6
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  path: /
  hosts:
    - chart-example.local

dummyUnUsed: test



