environment: production
businessUnit: finance
datacenter: dc1

# generator matrix values
generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
        matchExpressions:
          - key: environment
            operator: Exists
          - key: businessUnit
            operator: Exists
          - key: datacenter
            operator: In
            values:
              - dc1
  - list:
      elements:
        - folder: apps
        - folder: services